apiVersion: v1
kind: Service
metadata:
  name: service-nginx
  namespace: my-app-ns
spec:
  type: ClusterIP
  selector:
    app: this-label-needs-to-match-nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80