apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-service
  namespace: {{ .Values.global.namespace }}
spec:
  type: ClusterIP
  selector:
    app: phpmyadmin
  ports:
  - port: 80
    targetPort: 80